apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flagger
  namespace: linkerd
spec:
  interval: 10m
  url: https://github.com/fluxcd/flagger
  ref:
    semver: v1.x
  ignore: |
    /*
    !/kustomize
