apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd
configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - linker-stable-repository.yaml
  - linkerd-release.yaml
  - linkerd-viz-release.yaml
secretGenerator:
  - name: linkerd-certs
    files:
      - ca.crt
      - ca.key
      - issuer.crt
      - issuer.key
