apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
spec:
  dependsOn:
    - name: linkerd2
  interval: 5m
  chart:
    spec:
      version: "2.x"
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd2-stable
      interval: 60m
  # https://artifacthub.io/packages/helm/linkerd2/linkerd-viz
  values:
    grafana:
      enabled: true
    prometheus:
      enabled: true
