apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd2
spec:
  interval: 5m
  chart:
    spec:
      version: "2.x"
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd2-stable
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://artifacthub.io/packages/helm/linkerd2/linkerd2
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    installNamespace: false
    identity:
      issuer:
        crtExpiry: "2025-05-31T10:29:51Z"
